# Generated by Django 5.0.4 on 2024-05-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_equipment_status_alter_equipment_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
