# Generated by Django 5.0.4 on 2024-05-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_gallery_delete_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
