# Generated by Django 5.0.4 on 2024-05-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_gallery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='paymentStatus',
        ),
    ]
